const inquirer = require("inquirer");
const fs = require('fs');
const { promisify } = require("util");
const writeFile = promisify(fs.writeReadMe)
// array of questions for user
const questions = () => {
    return inquirer.prompt([
        {
            type: 'input',
            name: 'Description',
            message: 'How would you Describe this project?',
        },
        {
            type: 'input',
            name: 'projectName',
            message: 'What is the name of your project?'
        },
        {
            type: 'input',
            name: 'Installation',
            message: 'How would someone install this?'
        },
        {
            type: 'input',
            name: 'Purpose',
            message: 'What does this project do?'
        },
        {
            type: 'list',
            name: 'License',
            message: 'License for this project:',
            choices: [
                "Open",
                "Closed"
            ]
        },
        {
            type: 'input',
            name: 'Creators',
            message: 'Who created this project?'
        },
        {
            type: 'input',
            name: 'How do I test',
            message: 'How would I test this project?'
        },
    ]);
};


// function to write README file
function writeToReadME(answers) {
    return `
    <h1 align="center">${answers.projectName} </h1>

## Description
 ${answers.Description}

## Table of Contents
- [Description](#description)
- [Installation](#installation)
- [Usage](#usage)
- [Contributing](#contributing)

## Installation
 ${answers.Installation}

## Purpose
 ${answers.Purpose}

## Contributing
 ${answers.contributing}

## Tests
 ${answers.tests}

_This README was generated by [ReadME-Gen](https://github.com/SternTaylor/ReadME-Gen)
    `;
  }
  
    module.exports = writeToReadME;

// function to initialize program
async function init() {
 try {
     const answers = await questions();
     const writeToReadME = writeToReadME(answers);
     await writeFile('../READ.ME', writeToReadME);
    } catch(err) {
        console.log(err);
    }
}

// function call to initialize program
init();


//Used github.com/JPD61/README-generator As a guideline. This module I encountered many errors
//It made it hard to under stand when most of my time was being spent on trying to get it to work
//I followed all the steps but to me they were unclear on where to insert code and what to delete


//Side note- Past two weeks I had to get a new job, and the hours don't work as well for school anymore so it has
//touch balancing it out. This week I will push through module 10 and come back to this and previous modules.

//Thank you for reading, Taylor Stern